export default {
  BridgeSellLogo: require('../assets/images/BridgeSellLogo.png'),
  Screenshot20210118At103737PM: require('../assets/images/Screenshot20210118At103737PM.png'),
  Night: require('../assets/images/Night.png'),
  Evening: require('../assets/images/Evening.png'),
  Morning: require('../assets/images/Morning.png'),
  Education281329: require('../assets/images/Education281329.jpg'),
  LogoB: require('../assets/images/LogoB.png'),
  DraftbitIcon: require('../assets/images/DraftbitIcon.png'),
  _8: require('../assets/images/8.jpg'),
  DraftbitLogo: require('../assets/images/DraftbitLogo.png'),
  QAPTWeek1: require('../assets/images/QAPTWeek1.png'),
  QAPTThirdweek: require('../assets/images/QAPTThirdweek.png'),
  QAPTSecondweek: require('../assets/images/QAPTSecondweek.png'),
  QuantenatmungPrimetimeQuantenAtmungPrimarTaktungEinfuhrungAlbumCover: require('../assets/images/QuantenatmungPrimetimeQuantenAtmung.png'),
  ANU: require('../assets/images/ANU.jpg'),
  _1: require('../assets/images/1.png'),
  QAPt: require('../assets/images/QAPt.png'),
  _4: require('../assets/images/4.png'),
  Logobannerqapt: require('../assets/images/Logobannerqapt.png'),
  _3Copy: require('../assets/images/3Copy.png'),
  _2: require('../assets/images/2.png'),
  _2Copy: require('../assets/images/2Copy.png'),
  _1: require('../assets/images/1.png'),
  _1Copy: require('../assets/images/1Copy.png'),
};
